# Generated by Django 5.1.2 on 2024-10-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rewards_rate', models.CharField(max_length=100)),
                ('introductory_offer', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reward_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_habits', models.CharField(max_length=255)),
                ('credit_score_range', models.CharField(max_length=50)),
                ('desired_rewards', models.CharField(max_length=50)),
                ('monthly_budget', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
